# Generated by Django 4.1.2 on 2023-06-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('cliente', models.CharField(max_length=255)),
                ('reportado_por', models.CharField(max_length=255)),
                ('consultor', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('EN_PROCESO', 'En proceso'), ('NUEVO', 'Nuevo'), ('ACCION_CLIENTE', 'Acción de cliente'), ('ESCALADO_SAP', 'Escalado a SAP'), ('RESUELTO', 'Resuelto')], max_length=50)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('seccion_texto', models.TextField()),
                ('adjunto', models.FileField(blank=True, upload_to='adjuntos/')),
            ],
        ),
    ]
